# config.yaml

# General DEM parameters
num_dems: 1
size: 100
hilliness_range: [2, 8]

# Simulation evolution
total_iterations: 150
river_freq: 25

# Smoothing parameters
default_smoothing_strength: 1.0
light_smoothing_strength: 0.5

# River carving parameters
river_step_range: [-10, 10]
river_slope_ratio_range: [1, 4]
river_max_steps: 64  # Example: size // 2

# Edge trimming
trim_width: 5
